=== trilloner/oop-java-tasks/labs/xml_parser/src/main/resources/GreenHouse.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
>

    <xs:simpleType name="soilRestriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PODZOLIC"/>
            <xs:enumeration value="GROUND"/>
            <xs:enumeration value="SODPODZOLIC"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="multiplyingRestriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="LEAVES"/>
            <xs:enumeration value="CUTTINGS"/>
            <xs:enumeration value="SEED"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="lightRestriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="temperatureRestriction">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="0.0"/>
            <xs:maxInclusive value="30.0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="waterRestriction">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="100"/>
            <xs:maxInclusive value="2000"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="sizeRestriction">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="0.0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="flowers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="flower" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>

                            <xs:element name="soil">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="soilRestriction"/>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="origin" type="xs:string"/>

                            <xs:element name="visual-parameters">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="stemColor" type="xs:string"/>
                                        <xs:element name="leaveColor" type="xs:string"/>

                                        <xs:element name="size">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="sizeRestriction"/>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="growing-tips">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="temperature">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="temperatureRestriction"/>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name="light">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="lightRestriction"/>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name="watering">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="waterRestriction"/>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="multiplying">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="multiplyingRestriction"/>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== trilloner/oop-java-tasks/labs/xml_parser/target/classes/GreenHouse.xml
<?xml version="1.0" encoding="UTF-8"?>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="GreenHouse.xsd">
    <flower id="1">
        <name>Rose</name>
        <soil>GROUND</soil>
        <origin>Ukraine</origin>
        <visual-parameters>
            <stemColor>Pink</stemColor>
            <leaveColor>Gray</leaveColor>
            <size>10</size>
        </visual-parameters>
        <growing-tips>
            <temperature>10.0</temperature>
            <light>true</light>
            <watering>100</watering>
        </growing-tips>
        <multiplying>CUTTINGS</multiplying>
    </flower>

    <flower id="2">
        <name>Violet</name>
        <soil>PODZOLIC</soil>
        <origin>Brazil</origin>
        <visual-parameters>
            <stemColor>Green</stemColor>
            <leaveColor>Purple</leaveColor>
            <size>8</size>
        </visual-parameters>
        <growing-tips>
            <temperature>12.0</temperature>
            <light>true</light>
            <watering>500</watering>
        </growing-tips>
        <multiplying>LEAVES</multiplying>
    </flower>

    <flower id="3">
        <name>Tulip</name>
        <soil>SODPODZOLIC</soil>
        <origin>Australia</origin>
        <visual-parameters>
            <stemColor>Green</stemColor>
            <leaveColor>Red</leaveColor>
            <size>15</size>
        </visual-parameters>
        <growing-tips>
            <temperature>17.0</temperature>
            <light>false</light>
            <watering>1000</watering>
        </growing-tips>
        <multiplying>LEAVES</multiplying>
    </flower>

</flowers>
